#define MOD_VERSION_MAJOR 0
#define MOD_VERSION_MINOR 6
#define MOD_VERSION_BUILD 0
#define MOD_VERSION_REVSN 0

#define GAME_VERSION_MAJOR 1
#define GAME_VERSION_MINOR 8
#define GAME_VERSION_BUILD 9
#define GAME_VERSION_REVSN 0

#define STRINGIZEI(x) #x
#define STRINGIZE(x)  STRINGIZEI(x)

#define STRINGIZE_VERSION(a, b, c, d) STRINGIZE(a) "." STRINGIZE(b) "." STRINGIZE(c) "." STRINGIZE(d)

#define MOD_VERSION  STRINGIZE_VERSION(MOD_VERSION_MAJOR,  MOD_VERSION_MINOR,  MOD_VERSION_BUILD, MOD_VERSION_REVSN)
#define GAME_VERSION STRINGIZE_VERSION(GAME_VERSION_MAJOR, GAME_VERSION_MINOR, GAME_VERSION_BUILD, GAME_VERSION_REVSN)
