#define MOD_VERSION_MAJOR 0
#define MOD_VERSION_MINOR 10
#define MOD_VERSION_BUILD 0
#define MOD_VERSION_REVSN 0

#define GAME_VERSION_MAJOR 1
#define GAME_VERSION_MINOR 9
#define GAME_VERSION_BUILD 5
#define GAME_VERSION_REVSN 0

#define STRINGIZEI(x) #x
#define STRINGIZE(x) STRINGIZEI(x)
#define STRINGIZE_VERSION(v) STRINGIZE(v##_MAJOR) "." STRINGIZE(v##_MINOR) "." STRINGIZE(v##_BUILD) "." STRINGIZE(v##_REVSN)

#define MOD_VERSION  STRINGIZE_VERSION(MOD_VERSION)
#define GAME_VERSION STRINGIZE_VERSION(GAME_VERSION)
