#macro SCREEN_WIDTH 384
#macro SCREEN_HEIGHT 216

#macro SUB_ONLINE_INIT 0
#macro SUB_ONLINE_ERROR -1

#macro SUB_ONLINE_INITIAL_SEARCH 1
#macro SUB_ONLINE_LIST 2
#macro SUB_ONLINE_CREATING_LOBBY 3
#macro SUB_ONLINE_JOINING_LOBBY 4
#macro SUB_ONLINE_AUTOMATICALLY_JOINING_LOBBY 5
#macro SUB_ONLINE_VERSION_ERROR 6

#macro SUB_ONLINE_LOBBY 1
#macro SUB_ONLINE_SET_START_GAME_SETTINGS 2
#macro SUB_ONLINE_SET_STARTING_GAME 3
#macro SUB_ONLINE_CONNECTING 4
#macro SUB_ONLINE_COMPAT_WARNING 5

#macro ONLINE_REQUEST_TIMEOUT 6000
#macro ONLINE_CONNECT_TIMEOUT 12000
#macro ONLINE_SYNC_FILES_TIMEOUT 30000

enum GetInputType
{
    None,
    NoOnline,
    NoPlayback,
    Raw
}

enum Command
{
    None    = 0,
    Back    = 1,
    Unpause = 2,
    Reset   = 3,
    SetSel  = 4,
}
